dfinity/gix-components

.github/workflows/nightly.yml, scripts/package-next, scripts/update-version.mjs
Package and publish to npm a next version.
- I called it `next` and not `nightly` even though this PR builds the library at midnight. We might have the need to build it twice a day, therefore though about using `next` which is more generic.
- @bitdivine this PR need the npm `NODE_AUTH_TOKEN` to be added to the repo, can you do so at the same time that you review the PR?
- add scripts to package and publish to npm
=> build: next

src/lib/components/Layout.svelte, src/lib/styles/global.scss, src/routes/components/layout.md
For backwards compatibility, the design system needs to support the old layout as well.
- add property `modern=true` to `<Layout />` and unset padding and margin on `main` element if old layout
=> feat: support for deprecated layout

src/docs/styles/docs-global.scss, src/lib/components/MenuItem.svelte, src/routes/__layout.svelte, src/routes/components/layout.md
In the docs showcase the links in the menu were displayed with a primary color and text-decoration underline if hovered.
This is is not the expected behavior - i.e. no text-decoration and no color change.
This PR also fix a typo in the docs for the menu-items slot name.
- fix style colors in `docs` menu
- ensure `text-decoration` in `<MenuItems />`
- correct `menu-items` slot name in docs
- reorg style from `docs` layout to global scss
=> style: links text-decoration and docs

.github/workflows/nightly.yml, package-lock.json, package.json, scripts/update-version.mjs
We might need sometimes to release during the day the next version if we are blocked. This PR adds the manual trigger to the GitHub actions to do so.
- add manual trigger to github actions
- update version script to handle multiple next version the same day
=> build: manually trigger publish to npm

src/lib/components/Layout.svelte, src/routes/__layout.svelte, src/routes/components/layout.md
Components:
- The layout should redirect the toolbar `end` slot  so that the consumer can use it - e.g. to display a user button
- Simplify the usage of the back action. Instead of passing a slot, add the `<Back />` component in the layout
Docs:
- While developing this noticed there was an issue in the `docs` website regarding the back button
Components:
- add a `slot=toolbar-end` in the layout that target the `toolbar=end` (exposing "end" felt a bit generic so I gave it another name in the layout)
- include back button in layout
- modify docs accordingly
Docs:
- fix back action in the docs website
=> feat: toolbar end and back button

src/lib/components/Menu.svelte, src/lib/icons/IconClose.svelte, src/tests/components/Menu.spec.ts
When the menu is not sticky, a "close" button is displayed within the overlay menu as 
- copy "close" icon and action as in nns-dapp
=> feat: menu close action if not sticky

scripts/package-next
The modified version is overwritten by the package step. We should first package and then update the version number. This is different than in nns-dapp or ic-js.
=> build: package first and then update version

.github/workflows/nightly.yml
To publish to npm the job needs to find place in sub-folder `package`
- working dir property was not set correctly
=> build: fix ci working dir

.github/workflows/nightly.yml
The publish to npm is failing (see https://github.com/dfinity/gix-components/runs/7750678770?check_suite_focus=true). Most probably because the token is set to the root and not the working directory `package`.
- set `npmrc` in working dir
=> build: fix npm missing user

src/lib/components/SplitPane.svelte, src/lib/styles/global/layout.scss
The layout overflow-y scrollbar of the new design is incorrectly displayed within the viewport.
- overflow `content` instead of `main`
Is:
After this PR:
=> style: fix layout overflow-y

src/lib/styles/global/grid.scss
article height in grid are not correctly inherited and not strech neither.
is:
will be fixed has:
=> style: fix grid article height

src/lib/components/InfiniteScroll.svelte, src/routes/components/infinite-scroll.md
In the new ui we will have to use the infinite scroll as grid too.
- add a `layout` property to `<InfiniteScroll />` component (`list` or `grid`)
=> feat: infinite scroll grid option

src/lib/components/InfiniteScroll.svelte
The class should receive the value of the prop.
- `class:layout` renders `class="layout" we want `class={layout}` to render the value
=> fix: class layout

src/lib/styles/global/grid.scss
The selector was valid for infinite scroll grid but not normal grid.
- update card selector in grid to apply margin and height
is:
fixed:
=> style: fix card height in grid

src/lib/components/Layout.svelte, src/lib/components/SplitPane.svelte, src/lib/styles/global/layout.scss, src/routes/__layout.svelte, src/routes/components/layout.md
The footer of the legacy layout is broken - i.e. is not sticky anymore.
- defer the responsibility to the consumer to use the `main` and `footer` elements
- add a `scrollable-content` to the split pane (otherwise footers position absolute won't be sticky)
- rename `nns` option in `legacy`
=> fix: layout legacy footer

src/lib/components/Card.svelte, src/lib/components/InfiniteScroll.svelte, src/lib/styles/mixins/_card.scss, src/routes/components.svelte, src/routes/components/card.md, src/routes/components/infinite-scroll.md, src/routes/components/layout.md
Moving `_card.scss` mixins to `gix-components` and made few style adjustment for the new design ("list of proposals")
lib:
- move `_card.scss` from nns-dapp to gix-components
- add new mixin `meta` for "list of proposals"
- make card > article a `display: flex + flex-direction: column` so that the last meta can be aligned bottom. This potentially impact all cards but as far as I tested, they all actually already follow that column layout
docs:
- `<Card />` component documentation
lm
=> feat: cards mixins and style

src/lib/styles/global.scss, src/lib/styles/global/grid.scss, src/lib/styles/global/theme.scss, src/lib/styles/global/utility-classes.scss, src/lib/styles/global/variables.scss, src/routes/utility-classes.svelte, src/routes/utility-classes/cells.md
Introduce class utilities for common grids' cells and give spacing to the grid.
- lib: add cells utils classes
- lib: move text opacity utils classes to new global `utilitiy-classes.scss`
- lib: increase gap for the grid (value closer to figma design)
- docs: briefly document cells
- lib: add content-e and content-f to grid (for the position of the payload in the new proposal detail page)
=> feat: cells utility classes and grid spacing

src/lib/components/InfiniteScroll.svelte, src/lib/constants/constants.ts, src/routes/components/infinite-scroll.md, src/tests/components/InfiniteScroll.spec.ts, src/tests/components/InfiniteScrollTest.svelte
Make the `<InfiniteScroll />` component compatible for both list and grid. To do so, update behavior to observe last element of the container.
- observe last element of the container instead of calculated position
- remove unused constants
- `disconnect` on `beforeUpdate` instead of `afterUpdate` to prevent the component to emitting on layout shift
- add cmp property `disabled` to disable observation ("to disable the component when everything is fetched")
=> feat: infinite scroll observe last element

src/lib/components/SkeletonText.svelte, src/lib/index.ts, src/routes/components.svelte, src/routes/components/skeleton-text.md, src/tests/components/SkeletonText.spec.ts
Add the skeleton component to gix-components.
The component was copied from NNS-dapp but instead of rendering a sole `span` it has been upgraded to support different types of HTML elements. This will be useful for the new proposal detail page.
- lib: copy NNS-dapp `<SkeletonParagraph />` to `<SkeletonText />`
- lib: add option to render `span`, `p` or `h1-3`
- docs: add new doc page to document option and showcase
=> feat: skeleton text

src/lib/styles/themes/light.scss
The `--line` color in light mode currently equals the one of `--dark`. It should equals the color of `--disable` in `--light`. There was a copy/paste typo when introduced in previous PR.
- fix light color for `--line`
=> style: fix line color in light mode

src/lib/components.ts
The export for the `BottomSheet` got lost in PR https://github.com/dfinity/gix-components/pull/54
- redo export of `BottomSheet`
=> fix: missing bottom sheet export

src/lib/components/BottomSheet.svelte, src/lib/components/SplitPane.svelte, src/lib/stores/layout.store.ts
Adapt content height and scroll length if a bottom sheet is presented.
- add a new store for the layout bottom offset
- update offset according window width and bottom sheet height in component
- add padding bottom to content
=> feat: content height and scroll length with bottom sheet

src/lib/styles/global/variables.scss
Toast should be over modal except if the modal source is in a bottom sheet.
- redo z-index modal
will be:
=> style: fix z-index modal bottom sheet toast

src/lib/components/HeaderTitle.svelte, src/lib/components/Toolbar.svelte
The header now supports only one line.
- update tootlbar and header style
=> style: fix header title single line overflow

src/lib/components/Toasts.svelte, src/lib/styles/global/variables.scss
In case of errors display the toasts always on the top including above modals.
- split `z-index` for toasts in two, one for normal behavior one for errors
=> feat: in case of errors display toasts on top

src/lib/styles/global/layout.scss
Because of no z-index on the header the shadow is not visible. The shadow was moved to the `::after` block.
- move box shadow to the `after` component
=> fix: missing shadow

src/lib/components/Modal.svelte, src/lib/styles/global/modal.scss, src/routes/components/modal/+page.md
Discussed with Mischa, the modal's toolbar should not be sticky in case of dialog.
In case of alert, we keep a sticky option for backwards compatibility and time being.
- rename `toolbar` slot to `footer` for "alert" (breaking change will need a pr in nns-dapp)
- add utility class `.toolbar` for "dialog"
=> feat: modal toolbar sticky only for alert

src/lib/components/Toasts.svelte
Linter detected a potential issue in the comparison of the toasts
- compare if find is `undefined`
=> fix: toast has error

src/lib/components/Modal.svelte
We don't have it yet with the new modal but I guess we will.
- fix modal height
=> style: fix modal height

.github/workflows/publish.yml, src/lib/components.ts, src/lib/components/Input.svelte, src/lib/components/InputRange.svelte, src/lib/styles/mixins/_form.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss, src/routes/components/+page.svelte, src/routes/components/input-range/+page.md, src/routes/components/input/+page.md, src/tests/components/Input.spec.ts, src/tests/components/InputRange.spec.ts, src/tests/components/InputRangeTest.svelte, src/tests/components/InputTest.svelte, src/tests/components/InputValueTest.svelte
- Add `<Input />` and `<InputRange />` to `gix-components`
- Review input range design to be able to use it in dark mode with new design
lib:
- move `<Input />` and `<InputRange />` from NNS-dapp
- adapt input to make it agnostic
- review range style
- rename CSS variable for input box shadow (will have to be adapted in NNS-dapp)
doc:
- add new related pages
=> feat: input and range

src/lib/components/Modal.svelte, src/lib/styles/global/modal.scss, src/lib/styles/global/variables.scss
The dialog modal new design is too wide for Transactions in NNS-dapp on larger (> medium) screen.
We can also deprecate the wizard style and generally style form in modal.
- make dialog height fit-content on large screen
- set previous max-height as mix-height to smooth the opening transition
- replace wizard style with form style
Is:
Will be:
=> style: dialog bigger height and wizard form

README.md, jest-setup.ts, package-lock.json, package.json, src/lib/components.ts, src/lib/components/Html.svelte, src/lib/utils/html.utils.ts, src/routes/components/+page.svelte, src/routes/components/html/+page.md, src/tests/lib/components/Html.spec.ts, src/tests/lib/utils/html.utils.spec.ts
`Html` component with sanitizing. To avoid direct usage of `@html`.
- move and refactor `DOMPurify` usage from `nns-dapp`
- move `sanitize` util function from `nns-dapp`
- Html component
- sanitize()
=> Html component

src/lib/components/SplitPane.svelte
On large screen the content needs also to amend the banner height (when displayed) in its offset.
Is
Will be
=> style: banner offset

src/lib/styles/global/theme.scss
Remove `height` to fix toast message scrollbar.
- remove custom `height`
=> style: remove scrollbar thumb height

src/lib/styles/global/fonts.scss
Font size < 16px in inputs makes iOS automatically ping zoom for a11y reason. We do not want such issue.
https://css-tricks.com/16px-or-larger-text-prevents-ios-form-zoom/
Therefore we revert to a base font size of 16px.
=> style: revert base font size 16px

src/lib/styles/global/grid.scss
Fix the broken summary position on FF ([screen 1](https://github.com/dfinity/gix-components/pull/112#:~:text=Screenshots-,Before,-After), worse on android FF)
- `min-width: 0;`
Tested on 
- Desktop: FF, chrome, safari
- Android: FF, chrome
=> fix: broken summary position on FF

package-lock.json, package.json, src/lib/components/Backdrop.svelte, src/lib/components/Layout.svelte, src/lib/components/SplitPane.svelte, src/lib/styles/mixins/_interaction.scss
- improve user experience when the menu pushes the content on mobile devices
- improve user experience glitch when menu is open on small window, then user navigate and browser is resized and back button is still displayed
- use the `<Backdrop />` component in the `<SplitPan />` but animate with CSS only and not with JavaScript / Svelte to have a smooth behavior without the need to observe window size with JS
If user as a small window, open the menu, make the window bigger, then navigate, then make the window smaller, the "back" button and menu open are going to be displayed. I think it's an acceptable edge case - i.e. a pure CSS solution is better than a JavaScript less smooth solution.
=> feat: backdrop over content if menu open on small devices

src/lib/styles/global/variables.scss
Fix max height for dialog on iOS.
Before
After
=> style: dialog max height on iOS

src/lib/components/MenuItem.svelte
`<MenuItem />` are rendered under background on small height devices.
- add a z-index
Before
After
=> style: fix menuitems z-index

src/lib/components/Content.svelte
NNS-dapp e2e are failing https://github.com/dfinity/nns-dapp/actions/runs/3488539088/jobs/5837488928
`z-index` ❤️
Before
After
=> style: fix content backdrop z-index

src/lib/components/Dropdown.svelte
Less padding in the dropdown to spare space and fix click on icon that had no effect anymore.
=> style: smaller dropdown and fix icon click

src/lib/components/Dropdown.svelte, src/routes/components/dropdown/+page.md
Add a `slot=start` to the `<Dropdown />` component. It will be use in PR https://github.com/dfinity/nns-dapp/pull/1548 on small devices to display the project logo within the dropdown.
=> feat: dropdown slot start

src/lib/components/Card.svelte, src/lib/components/Input.svelte
As reported on [twitter](https://twitter.com/DfinityToday/status/1595439754396729344), the ratio when the card is disabled is not good enough.
=> style: better disable card color ratio

src/lib/components/Dropdown.svelte, src/routes/components/dropdown/+page.md
Small dropdown fits well "project" selector but, do not fits well when used in modal.
- redo previous padding and make top/bottom stylable
=> style: dropdown redo height and option

src/lib/components/InfiniteScroll.svelte
We disable the `<InfiniteScroll />` component `beforeUpdate` because we do want to trigger an intersection in case of layout shifting - i.e. we do not want to trigger additional unexpected query and update calls in the proposal list views.
We noticed that under certain circumstances, notably when initialized while enabling at the same time, a race condition can lead to the scroller being disabled.
Root cause of the problem is a Svelte issue [#6016](https://github.com/sveltejs/svelte/issues/6016). Indeed, when bindings are used (`bind:this=my_HTML_element`) within the compoment, the `beforeUpdate` lifecycle is called twice while `afterUpdate` is called only once. Therefore, as we disable the scroll in the first method and enable in the second, the scroller remains disabled.
See PR #141 …
=> fix: InfiniteScroll disabled because beforeUpdate is called twice when bindings are used

src/lib/components/Header.svelte, src/lib/components/Toolbar.svelte
Give some spacing for the header borders on mobile devices as in design.
=> style: header border spacing as in design

src/lib/components/SplitContent.svelte, src/lib/styles/global/variables.scss
Fix width and adjust a bit wider.
Bad:
Better:
=> style: fix split content width

src/lib/components/StretchPane.svelte, src/tests/lib/components/HeaderTitle.spec.ts
Auto-imported path are incomplete which makes the lib hard to use locally in NNS-dapp.
=> fix: auto import incomplete path

src/lib/components/QRCode.svelte, src/lib/types/qr-creator.ts
The library leads to issues (es modules import error, segmentation fault, blocking tests etc.) in jest tests of NNS-dapp when use explicitly or imported implicitly.
Therefore, the simplest way to avoid these problems is to skip it globally in jest tests.
It remains tested in e2e tests.
P.S.: Mocking it would probably be possible but that way no one using the library as to care about this issue.
This PR solves both `npm run test` and `npm run build` of NNS-dapp.
- lazy load the `qr-creator` library for the browser only
=> build: make qr-creator available only in the browser

src/lib/components/Collapsible.svelte
A user noticed and reported on the [forum](https://forum.dfinity.org/t/modify-nns-front-code/18560) an issue with the `Collapsible` component which did not computed the expandable height correctly. I was able to reproduce it in Firefox only.
- fix height computation of the `Collapsible` element by using primarly the `getBoundingClientRect` API which according test seems more accurate on Firefox and compatible with Chrome, Safari and iOS
Bug
Fix
=> fix: collapsible calculated height on Firefox

src/lib/components/Modal.svelte, src/tests/lib/components/Modal.spec.ts
As requested, hide "Close" button if modal has disabled events (instead of disabling the button).
=> feat: hide close button if modal disabled

src/lib/stores/toasts.store.ts, src/tests/lib/stores/toasts.store.spec.ts
We will use this option to clean selected toast after sign-in in NNS-dapp (insted of reset() and workaround).
=> feat: add an option to clean selected toasts

src/lib/components/Input.svelte, src/tests/lib/components/Input.spec.ts
Avoid displaying initial icp amount in exponential form.
https://dfinity.atlassian.net/browse/GIX-1373
- apply exponentToPlainNumberString to initial icp value
- tests to cover this issue
before
after
=> feat: apply exponentToPlain for initial icp values

package-lock.json, package.json, src/lib/components/Card.svelte, src/lib/icons.ts, src/lib/icons/IconAdd.svelte, src/lib/styles/global/button.scss, src/lib/styles/global/grid.scss, src/lib/styles/global/variables.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss, src/routes/(page)/utility-classes/buttons/+page.md
New style for "button card".
PR also bump version of gix-cmp to release after merge.
- new style `button.card`
- few variable refactored to become global, notably card border size
- grid height set to `1fr` to be consistent
=> style: button card

src/lib/workers/qrcode.worker.ts
This morning I noticed some leading spaces in a QR code I scanned. Probably worth trimming the result so that user will not have to edit the input field afterwards to remove such empty characters.
=> feat: trim QR code reader result

src/lib/components/Copy.svelte
Preserve "Copy" button rounded nature even when use in flex container.
Is:
Afterwards:
=> style: copy button round in flex

src/lib/components/WizardModal.svelte, src/tests/lib/components/Modal.spec.ts, src/tests/lib/components/WizardModal.spec.ts
Currently, getting the root element of a WizardModal component by test ID requires adding an additional wrapping `div` to put the `data-tid` attribute on.
Since WizardModal already has a single root component, being able to set a test ID on that would remove the requirement of the extra div.
1. Pass testId from WizardModal to Modal
2. Add data-tid test to Modal
3. Add data-tid test to WizardModal
no visible changes
Unit tests for Modal and WizardModal
=> Pass testId from WizardModal to Modal

src/lib/components/QRCodeReader.svelte
Lazy load QR code reader to spare chunks when the component is not used.
QR code generator already implements such strategy.
- `await import` instead of static `import`
=> feat: lazy load QR code reader

src/lib/components/MenuBackground.svelte, src/lib/components/ThemeToggle.svelte, src/lib/stores/theme.store.ts, src/lib/utils/theme.utils.ts, src/tests/lib/components/MenuBackground.spec.ts
Despite loaded in root, the actual default value of the theme store is undefined.
- when built where no DOM exists, therefore cannot guess the theme
- when loaded in the browser, because of the chunking, might be loaded after other resources have already been loaded and displayed
This is what lead the menu background to be displayed in dark mode over a light theme.
- set `undefined` as default theme store value
- do not display menu background if theme is not set
I tried to add a `transition:fade` to makes the images appearing smooth but it had no effect.
Issue:
Solve:
=> fix: menu background loading glitch

src/lib/components/KeyValuePair.svelte
Was requested to center a key value pair for ckBTC.
- add `--key-value-pair-justify-content` CSS variable
=> style: add a CSS variable to justify key value pair

src/lib/styles/global/modal.scss
The modal being narrower on desktop and given the fact that we have to display more information in the transactions modal, setting a smaller gap between lines of `form` within modal fits better the display.
=> style: modal form gap narrower

src/lib/components/Modal.svelte, src/lib/components/WizardModal.svelte
The wizard modal opening is glitchy on desktop which really annoys me.
The wizard modal is glitchy because we noticed issue last year which we solved by wrapping the transition component within a `if` that became `true` only once the modal intro animation was done. This is the major root cause of the issue. Because the transition is not displayed, the slot it contains is not displayed and per extension the content is not displayed, therefore the height is not correct.
In addition to be glitchy, this is also an issue for the browser as if such guard is removed without further code, it can lead the browser to become irresponsive as the component transition ends in an infinite loop (⚠️ 🚨).
After opening and closing the modal a zillion times this afternoon I came to the conclusion that the …
=> fix: wizard modal glitch

src/lib/components/Collapsible.svelte, src/lib/components/KeyValuePairInfo.svelte, src/lib/components/TestIdWrapper.svelte, src/tests/lib/components/TestIdWrapper.spec.ts, src/tests/lib/components/TestIdWrapperTest.svelte
To improve testing, the testId must be in the most parent element.
In KeyValuePairInfo that means that the Collapsible should have the test id.
* Add prop testId in Collapsible.
* KeyValuePairInfo passes testId to parent Collapsible.
* No new tests required.
=> Feat: TestId changes in Collapsible and KeyValuePairInfo

.github/workflows/nightly.yml, .github/workflows/publish.yml, package-lock.json, package.json
Publish provenance alongside our libraries to npm.
- https://github.blog/2023-04-19-introducing-npm-package-provenance/
- https://github.blog/changelog/2023-04-19-npm-provenance-public-beta/
- add flag `--provenance` next to `npm publish`
=> build: publish to npm with provenance

.github/workflows/nightly.yml, .github/workflows/publish.yml
To use `provenance` the GitHub actions need specific `permissions`.
- https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
- https://github.blog/changelog/2023-04-19-npm-provenance-public-beta/
=> build: fix provenance

src/lib/components/Header.svelte
We want to refer to the header element from a corresponding page object in the nns-dapp repo.
Add `data-tid="header-component"` to `src/lib/components/Header.svelte`
=> Add data-tid to Header component

src/lib/components/Checkbox.svelte, src/routes/(split)/components/checkbox/+page.md
When a checkbox has a label that spans multiple lines, `align-items: center` looks strange.
When removing `align-items: center`, the single line labels also shift slightly.
I showed the difference to Mary and she told me to make the change for all checkboxes.
1. Remove `align-items: center` from `Checkbox.svelte` and use the default top alignment.
2. Add a showcase with a multi-line label.
Before:
After:
=> Top-align checkboxes

src/lib/components/Input.svelte, src/tests/lib/components/Input.spec.ts
Avoid exponential formatting for the icp values.
Original issuer: when a user clicks on the 'Max' button and has a very small amount of tokens left, the value appears in exponential format, which is incorrect. The fix checks and replaces any Xe-Y formatted value on change.
- apply optional formatting to input
- should avoid exponent formatted on change in icp mode
=> fix: optionally format raw input to normal number format

src/lib/components/BottomSheet.svelte
`<BottomSheet>` appears inline on large screens and docked to the bottom on small screens.
When it's docked to the bottom, it sets `$layoutBottomOffset` so layout components can take it into account.
`BottomSheet` listens to `innerWidth` of the window and `clientHeight` of the component.
In practice `clientHeight` is set first and since `innerWidth` is initialized to `0`, the code acts as if the screen is small until `innerWidth` is also set.
This means that on large screens, `$layoutBottomOffset` is briefly set to non-zero and then immediately back to `0` when `innerWidth` is set.
On CI (although I wasn't able to reproduce this on my Mac) this consistently results in the page being rendered twice.
And for some reason the second render happens before the first page is destroyed.
On the …
=> Fix BottomSheet race condition

src/lib/styles/global/button.scss
When hovered, the color of the links become `value`. This PR align the same color behavior for button of type text.
=> style: hover text button color

src/lib/components/Dropdown.svelte
The Dropdown page object should use a test ID to locate the Dropdown component.
Add `data-tid="dropdown-component"` attribute to the outer element of the Dropdown component.
N/A
=> Add data-tid to Dropdown component

package.json
Accept any `@dfinity/utils` to avoid conflicts in NNS-dapp.
=> build: accept any utils

src/lib/components/Value.svelte
I want to refer to a Value component from a page object in the nns-dapp repository.
Add `testId` prop which sets `data-tid` attribute to `Value` component.
N/A
=> Add testId to Value component

src/lib/components/Modal.svelte
I want to migrate `frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts` in nns-dapp to use page objects and I need a way to get to the title of a Modal for that.
Add `data-tid="modal-title"` on the title slot in `Modal.svelte`.
I ran `npm run dev` and verified that the title of the `WizardModal` component has the `datat-tid="modal-title"` attribute.
=> Modal data-tid on title

package-lock.json, package.json
Fix semver vulnerable to Regular Expression Denial of Service [CVE-2022-25883](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw).
- pin `semver` to v7.3.5
=> build: bump semver

src/lib/components/Modal.svelte
Content of the modal was not covering all the height of the modal.
* Add `flex: 1` to the content wrapper.
Before:
After:
=> Fix: Modal content height

src/lib/styles/mixins/_header.scss
On small devices the header button activated looks not round which is visually unpleasant.
Current
PR
=> style: fix header button width

src/lib/components/PageHeader.svelte
PageHeader responsiveness was not so great when the start and end slots had long content.
Solution: Change the rendering of the slots for small screens.
* Add media query in PageHeader to render start and end slots differently.
Desktop doesn't change.
Mobile:
=> Feat: Improve PageHeader responsiveness

src/lib/components/Backdrop.svelte, src/lib/components/BusyScreen.svelte, src/lib/components/Modal.svelte, src/lib/components/Popover.svelte, src/lib/components/Toast.svelte, src/lib/components/WizardTransition.svelte
Svelte transitions are executed by default in components regardless if their parent components destroy those or not. This behavior is known as the `|global` transitions setting and is the default in Svelte v3.
This leads to issue with the SvelteKit navigation because DOM elements might not be detached and related context might remain active.
We generally notice the issue in NNS dapp after navigation when the DOM wrongly contains two `split-pane` elements.
In Svelte v4 the default behavior was changed to `|local`. Setting that can already be used in v3 when explicitely set. This setting has for effect to not execute the transition and destroy the components if parents destroy those. i.e. to populate the destroy.
- documentation: https://svelte.dev/docs/v4-migration-guide#transitions-are-loc …
=> feat: set transitions as local

src/lib/components/Backdrop.svelte, src/lib/components/BusyScreen.svelte, src/lib/components/Modal.svelte, src/lib/components/Popover.svelte, src/lib/components/Toast.svelte, src/lib/components/WizardTransition.svelte
Set svelte animation `local` to `global` because of broken `introend` event.
- Revert #246
- local to global everywhere
No visual changes
=> Revert svelte animation local to global

src/lib/icons/IconHistoryToggleOff.svelte
Consistent icon sizes.
* Add a size prop to IconHistoryToggleOff component and set it the same default as other icons.
No changes in screenshots because screenshots set the same height and width for all icons.
=> Chore: Change default icon size

src/lib/icons/IconExpandCircleDown.svelte
We need different sizes of this icon.
* Add `size` prop to `IconExpandCircleDown`
No screenshot changes because default is the same.
=> Feat: Add size to IconExpandCircleDown

src/lib/components/ItemAction.svelte
The ItemAction should not stretch the actions slot.
* Remove `stretch` style in the actions slot.
No UI changes in desktop.
New UI in mobile:
=> Feat: ItemAction - do not stretch actions

src/lib/components/Card.svelte, src/routes/(split)/components/card/+page.md
Turns out we still need two icons in the `Card` component because those are used in the universe selector of NNS dapp.
=> feat: revert two icons in Card

src/lib/components/Card.svelte, src/routes/(split)/components/card/+page.md
Not really an issue when the all card is a text but, when only parts of it has no specific color, hover a card link has for effect to change the color which does not look that good on the NNS dapp launchpad.
=> style: card link hover color

src/lib/components/Copy.svelte
When the `Copy` component is used within an hyperlinks, as e.g. a card, it triggers both its copy action but also propagate the default behavior which has for effect to trigger the link.
=> fix: prevent default behavior of copy button

src/lib/components/Section.svelte, src/routes/(split)/components/section/+page.md
There is too much spacing when there is no description in the Section.
* New class to change margins when description slot is not present.
Before:
Now:
Now with and without:
=> Chore: Improve Section when no description

src/lib/styles/global/scrollbar.scss
Narrower scrollbars to avoid those behind partially cut by the UI components such as the islands.
=> style: narrower scrollbars

src/app.html, src/lib/components/Menu.svelte, src/lib/components/MenuBackground.svelte, src/lib/components/MenuItem.svelte, src/lib/stores/layout.store.ts, src/lib/stores/menu.store.ts, src/lib/styles/global.scss, src/lib/styles/global/menu.scss, src/lib/types/menu.ts, src/lib/utils/menu.utils.ts
Prefer usage of global CSS instead of JS to define the "collapsed" state of the menu, this to avoid glitch when deployed on mainnet.
=> feat: menu collapse global css

src/lib/icons/IconAccountsPage.svelte, src/lib/icons/IconCanistersPage.svelte, src/lib/icons/IconNeuronsPage.svelte, src/lib/icons/IconSettingsPage.svelte
The svg IconXxxPage was not appearing in Safari.
The problem is that the width and height were not defined in the svg and Safari needs it to be defined.
* Set a default size of 100% in the svgs so that the parent controls the size.
Both screenshots of Safari.
=> Fix: Show svg icon in Safari

src/lib/components/Card.svelte, src/routes/(split)/components/card/+page.md
Remove text color `inherit` on hover to have more predictable behaviour.
The plan is to avoid elements w/ inherit colors in the Card.link (e.g. `<dt>` should become `<dt class="description">`)
=> style: remove colour exception on hover

src/lib/components/PageBanner.svelte
The PageBanner as is couldn't go directly inside a flex container because of a height overflow in Safari.
More on the issue: https://stackoverflow.com/questions/62075401/safari-grid-in-flexbox-produces-height-overflow
The fix is to add a wrapper around the container of PageBanner.
No changes.
=> Fix: PageBanner for Safari

src/lib/components/Card.svelte, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Change the background color for the disabed cards. Those are used for the landing pages also.
* Add a new variable in both themes: `--card-background-disabled`.
* Use new variable in the Card when `disabled`.
Dark theme (before):
Dark theme (now):
Light theme (before):
Light theme (now):
=> GIX-1847: Change card disabled color

package.json, scripts/copy-workers.mjs
When we locally install gix-cmp in NNS dapp
```
$ npm install /Users/dskloet/dev/gix-components
```
the installation runs also the pre/post scripts of gix-cmp. As I added a post scripts to copy the web workers for the analyytics of the showcase, this script gets executed which is not necessary.
So to avoid this issue and because we only needs the web workers for the showcase, we can move the script from `postinstall` to a manually call after build.
- move script from `postinstall` to `build`
- do not print error in script if no error
=> build: copy workers after build instead of postinstall

scripts/copy-workers.mjs
#289 moved the copy from the workers from `postinstall` to a post build script but, since `static` files are moved to `build` output folders, the post script that copy to `static` has no effect. That's why the script should directly copy the files to the output.
=> build: fix copy workers

src/lib/components/Card.svelte, src/routes/(split)/components/card/+page.md
Fix the poor contrast on the token selector for ICP logo described here: https://dfinity.atlassian.net/browse/GIX-1864
Solution: add a stronger outline to the logo when selected and on hover.
Yet, to be able to know when the card is hovered, we can't rely on the hover of the content because the Card has some padding. Therefore, I'd like to add a `noPadding` prop to the Card component. This way, the child will manage the padding and can also manage the onhover of the whole Card.
* Add prop `noPadding` in `Card` component.
=> GIX-1864: Add property noPadding on Card

package-lock.json, package.json
There were major improvements in the Juno's analytics canister to improve scalability of the data. Those changes lead to few structure changes in the keys and entities which are reflected in the last version of the library.
So we need to bump the library to reactive the analytics for gix-cmp.
=> build: bump analytics

src/lib/components/ProgressBar.svelte, src/lib/index.ts, src/lib/types/progress-bar.ts
"Segment" is already a component. Therefore, I renamed the type to ProgressBarSegment.
* Rename type Segment to ProgressBarSegment.
No changes.
=> Fix: Rename Segment type due to conflict

package-lock.json
Fix security issues.
Only automatic changes after running `npm audit fix`
No changes.
=> Chore: Fix vulnerability issues

package.json, playwright.config.ts, src/docs/services/analytics.services.ts
Fix e2e error `[WebServer] Error: Not found: /components/workers/analytics.worker.js` by introducing a staging mode that can be use to build and run the test in order to avoid loading the analytics.
- add mode `stagin`
- build test with staging instead of build
- don't load anyltics on staging
=> build: fix running e2e locally with staging build env

src/lib/components/Island.svelte
I want to be able to make page objects for components which have an `<Island>` as their outer most element.
For this I need to be able to test a `data-tid` attribute on the outer element.
Add a `testId` prop to `Island` which sets a `data-tid` attribute on the outer `div`.
=> testId on Island component

src/lib/components/KeyValuePair.svelte, src/lib/components/KeyValuePairInfo.svelte, src/routes/(split)/components/key-value-info/+page.md
Add property `alignIconRight` to align info icons to the right
- alignIconRight
- align value text right to improve long text alignment (mobile screenshot)
=> Key value info align icon right

src/lib/components/KeyValuePairInfo.svelte
Remove unused prop to fix `<KeyValuePair> was created with unknown prop 'alignIconRight'` that breaks unit tests.
Cleanup
No changes, cleanup only
=> Remove relic prop

src/lib/components/Tag.svelte, src/lib/styles/global.scss, src/lib/styles/global/tag.scss, src/routes/(page)/utility-classes/+page.svelte, src/routes/(page)/utility-classes/tag/+page.md
Add `tag` utility class to be more customisable (e.g. themed colours).
- new utility class
- refactor `Tag` component to use `tag` class
=> style: add `tag` utility class

src/lib/components/Content.svelte, src/lib/styles/mixins/_layout.scss
Remove unexpected border on proposal detail page by fixing the bottom-offset calculation.
- new global variable `--content-margin` 
- update `--layout-bottom-offset` calculation in `Content.svelte`
Note: this variable is also used by `SplitContent` and `Toast` but it's always `0`.
=> fix: layout-bottom-offset wrong value

package.json, src/lib/components/InfiniteScroll.svelte, src/lib/components/Menu.svelte, src/lib/components/ProgressBar.svelte, src/lib/components/QRCode.svelte, src/lib/components/Tag.svelte, src/lib/components/Toasts.svelte
I noticed that Svelte files are not included in the `format` script anymore.
Opened an issue in the Svelte prettier plugin: https://github.com/sveltejs/prettier-plugin-svelte/issues/407
Meanwhile enforcing the types of the file to format solve the issue.
=> build: fix prettier format command not processing svelte files

src/lib/styles/global/colors.scss, src/lib/styles/themes/light.scss
Making color constants available to render icons like this:
Also the existing color of `--orange-tint` does not quite match what is defined in Figma.
1. Fix the value of `--orange-tint`.
2. Define `--pending-color` and `--pending-background`.
=> Add pending orange color constants

src/lib/styles/global/utility-classes.scss, src/routes/(page)/utility-classes/cells/+page.md
Add `content-cell-island__card` style to replace multiple custom styles (ex. `markdown-container`) in `nns-dapp`. 
- class `content-cell-island__card`
=> style: content-cell-island--highlighted style

svelte.config.js, tsconfig.json
Resolve lint warning:
> You have specified a baseUrl and/or paths in your tsconfig.json which interferes with SvelteKit's auto-generated tsconfig.json. Remove it to avoid problems with intellisense. For path aliases, use `kit.alias` instead: https://kit.svelte.dev/docs/configuration#alias
=> build: adapt alias for sveltekit v2

src/lib/styles/global/button.scss
There is an issue with the content of the button going over another element.
The problem is the `z-index` set in the `ghost` and `text` button utilities.
* Remove the `z-index` from the button styles.
No UI changes.
=> Feat: Remove z-index from button

src/lib/components/HeaderTitle.svelte, src/lib/styles/themes/light.scss, src/routes/(split)/components/header-title/+page.md
There were some issues with the new light theme colors.
* Fix typo with color `-124` when it shuold have been `-125`.
* Remove setting the color for the HeaderTitle.
* Change `--table-header-background` to `--cp-light-100`.
* Add the header title in the gix component page. This would have helped catch the issue.
Using the HeaderTitle in the component document page.
=> Fix: Colors

src/lib/styles/themes/light.scss
The card is not visible within an island for light theme.
In this PR, change the color of `--island-card-background` for the light theme.
* Change `--island-card-background` color for light theme.
There is how it will look now in NNS Dapp:
=> Fix: Change light island-card-background

src/lib/components/Input.svelte, src/routes/(split)/components/input/+page.md, src/tests/lib/components/Input.spec.ts, src/tests/lib/components/InputValueTest.svelte
I need more decimals in the input field of type icp and I don't want to ship a breaking change. 
So my first idea was to tweak the `inputType` set to `icp` but it leads to the issue with the scientific notation and I was concerned about making `icp` bind `value` of type `string` given that would break NNS dapp.
So ultimately I dediced to add a new `inputType` called `currency` which basically does the same thing as `icp` but, map the value to a `string`. That way we can avoid the issue of scientific notation. It's up to the consumer to use it correctly.
This PR also add a property to tweak the number of `decimals` accepted for input field type `currency`.
Both number of decimals and value parsed as number for `icp` remains that way the same.
- add new type `currency` which basically does …
=> feat: input type currency

src/lib/components/Input.svelte, src/routes/(split)/components/input/+page.md, src/tests/lib/components/Input.spec.ts
While testing the new input type `currency` in Oisy I landed on an that was parsed to number with scientific notation instead of binding the value to string. This happened when I entered a number with the max number of decimals and then trying to enter additional decimals.
For example: I entered 0.000000011231232121 in the input field, 18 decimals, and then tried to add a 19th decimals.
- in the input field hook `restoreFromValidValue`, map to number only for the `inputType` is `icp` - i.e. if `currency` keep string
- use renamed `decimals` property in the showcase
=> fix: trim currency decimals as string

e2e/input.e2e.ts, src/lib/components/Input.svelte, src/routes/(split)/components/input/+page.md, src/tests/lib/components/Input.spec.ts
While testing the new `currency` mode of the `Input` property in Oisy, I noticed two issues which are corrected by this PR.
Leading zeros were added to the binded property (entering 0. lead to 0.000000000000) and JS was rounding the number imprecisely even though this mode requires a string as output.
- use internationalization to wrap the decimals of the "currency"
Rounding issue:
Trim issue:
Fix:
=> fix: input currency decimals rounding and trim zero

src/lib/styles/global/colors.scss
the CSS rgb(`from <something>`) is not working in Firefox yet
Use the more traditional hex notation to be constant with the other colors.
=> replace color from notion so it would work in firefox

src/lib/styles/global/button.scss, src/lib/styles/global/link.scss, src/lib/styles/mixins/_button.scss
Add `a.button.text` class to mimic text buttons for links.
- moved `button.text` to mixins to reuse for links
- add `a.button.text`
=> Button class text for links

src/lib/components/Popover.svelte
Increase `Popover` max-width to support wider content (like a redesigned account menu - screenshot)
- replace fixed width with all `available space - right` to make it nicely shrink on mobile (screen 2).
=> style: increase popover max-width

src/routes/(page)/browser/+page.svelte, src/routes/(page)/resources/+page.svelte
A page that can be used to determine capatibilities of the browsers used by users of NNS dapp / gix-cmp.
Useful for example to debug issue related to device detection such as if a device is mobile or desktop.
Demo: https://gix.design/browser
=> feat: browser detection

src/lib/components/Input.svelte, src/routes/(split)/components/input/+page.md, src/tests/lib/components/Input.spec.ts
Disable per default 1Password in input fields.
- add ignore flag as described in 1Password documentation https://developer.1password.com/docs/web/compatible-website-design/
This solve following:
=> feat: ignore 1Password in input fields

package-lock.json, package.json, src/app.d.ts, src/lib/components/QRCodeReader.svelte, src/lib/utils/device.utils.ts
We received reports from users complaining about the QRCode reader being incorrectly mirrored on their devices. This issue was specifically noted on Samsung devices that support a stylus. The presence of a stylus leads the device to report to the user agent that it supports `any-pointer:fine`, i.e. it indicates support for a "mouse", which we previously used to detect desktop environments.
This PR revises our method for detecting mobile devices by utilizing the `NavigatorUAData` agent, which is available in Chrome. It also updates our approach for identifying desktop devices to correct the QRCode reader mirroring issue.
This implementation comes with a tradeoff. Since `NavigatorUAData` is not yet supported in Firefox, using this browser on a touchscreen device will result in it being …
=> feat: improve mobile and desktop detection for QRCode reader mirroring

src/lib/styles/mixins/_toolbar.scss
Update tooltip styles to fix multiple alignment issues:
- set width for all `button` tags `00% on  mobile and control 1 level elements width w/ flex
- reset width for bigger breakpoints to use buttons content size.
- styles of .toolbar
---
---
---
---
=> style: apply extra styles to the buttons/tooltip only

src/lib/styles/themes/dark.scss
UX asked to update these colors.
Changed some dark theme variables.
Light theme should remain as is.
Old:
New:
=> GIX-2293: Update table colors

src/lib/components/Popover.svelte
Artem asked me to remove the box-shadow on the Popover.
Until recently the Popover always had a visible dark backdrop where the box-shadow wasn't really visible anyway so this should only make a difference for the new cases where we hide the backdrop.
Remove `box-shadow` style on `Popover`.
Before:
After:
=> Remove box-shadow on Popover

.eslintrc.cjs, src/tests/lib/components/Input.spec.ts
Prevent usage of `console.log` with eslint (given that I spotted a console.log in a test while developing an unrelated feature).
=> chore: prevent console log usage with eslint

src/lib/components/Tooltip.svelte
Lint currently detects an error on `main`:
```
/Users/daviddalbusco/projects/dfinity/gix-components/src/lib/components/Tooltip.svelte:69:31
Error: Argument of type 'HTMLDivElement | undefined' is not assignable to parameter of type 'Node'.
Type 'undefined' is not assignable to type 'Node'. (ts)
// Move tooltip to the body to avoid it being cut off by overflow: hidden.
document.body.appendChild(tooltipComponent);
});
```
=> chore: solve lint error type 'undefined' is not assignable to type 'Node'

src/lib/styles/global/colors.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Change colours related to the main navigation to fix dots visibility and improve contrast.
nns-dapp sibling pr that will utilise this - https://github.com/dfinity/nns-dapp/pull/4753
- change menu selection colour (will be also used for the mobile navigation dropdown background)
- update the colour of the split container (used only for universe list)
- cleanup
=> Update colours 2024 04 22

src/lib/components/Tooltip.svelte
If an element has a `title` attribute, the browser generates some kind of tooltip for it if you hover for a long time.
If this is done on the parent of a tooltip target, it can interfere with the actual tooltip.
Add an empty `title` attribute on the tooltip target to prevent multiple tooltips from showing.
Before:
https://github.com/dfinity/gix-components/assets/122978264/d3a82b5f-aac7-4293-9d4e-a84f28eae562
After:
https://github.com/dfinity/gix-components/assets/122978264/75c84c67-d4b9-4c4a-88b4-46a24fb167b2
=> NNS1-2966: Empty title on tooltip target

src/lib/components/WizardTransition.svelte, src/tests/lib/components/WizardModal.spec.ts
In Oisy, I need to target the `div` container meant for transition within the `WizardModal` for custom styling purpose.
- add a class to div
- adapt types in test given that Webstorm was displaying some warnings
=> feat: add a class selector for wizard transition container

src/lib/components/Modal.svelte, src/tests/lib/components/Modal.spec.ts
Do not close the modal when the 'Escape' key is pressed if the busy store is active. This ensures the same behavior as when the close button is covered by the busy overlay.
- Check for `busy` before close.
- Text added.
- no visible changes
=> Skip modal close on Esc when busy

src/lib/components/Modal.svelte
Fix lint error:
> /Users/daviddalbusco/projects/dfinity/gix-components/src/lib/components/Modal.svelte:35:28
> Error: Binding element 'key' implicitly has an 'any' type. (ts)
>
>  const handleKeyDown = ({ key }) => {
>    // Check for $busy to mock the same behavior as the close button being covered by the busy overlay
=> chore: modal lint error

src/lib/icons/IconVote.svelte
We need to display a vote icon in a select actionable button at a non-standard size.
- Add a `size` prop (tested manually).
=> feat: VoteIcon size param

src/lib/components/Modal.svelte
There is a bug that causes nns-dapp to crash. It’s possible to reproduce it locally against the dev version. It seems to be a weird Svelte behavior during unsubscribing from the store inside the window listener, but no real proof of this has been found. However, removing the store subscription leads to normal nns-dapp behavior without crashes.
How to reproduce the bug:
1. Sign into https://nns.ic0.app/
2. Click on Internet Computer
3. Click on “Receive”
4. Click on “Finish”
5. The site crashes.
- Replacing `$` with `get(store)`.
- Manually tested.
=> Use get instead of $

src/routes/(page)/styling/usage/+page.md
The styles are shipped within a dist folder.
- correct typo in documentation
=> docs: correct typo in global import

src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
These colors are used in the neurons table.
Define `--text-description-tint` for light and dark theme as defined in Figma.
=> Define --text-description-tint colors

src/lib/components/Tooltip.svelte, src/tests/lib/components/Tooltip.spec.ts, src/tests/lib/components/TooltipTest.svelte
Every tooltip must have a unique ID so the target can be correctly associated with the tooltip through `describedby`.
Giving a unique ID to a tooltip in a component that appears multiple times on the page, can be tedious.
1. Add `idPrefix` prop to `Tooltip` and make `id` optional. If `id` is not specified, a unique ID is automatically generated by combining the prefix with a sequence number. For backwards compatibility, if `id` is specified, it's used as is.
1. Unit tests were added.
2. Tested in nns-dapp repo.
=> Add idPrefix prop to Tooltip

src/lib/styles/global/colors.scss
`--cp-light-600` and `--cp-dark-500` have comments saying they are not used.
`--cp-light-600` is used [here](https://github.com/dfinity/gix-components/blob/40f7fdf3c93210c58e59e566b1f73a9953b9990a/src/lib/styles/themes/light.scss#L8-L9).
`--cp-dark-500` is used [here](https://github.com/dfinity/gix-components/blob/40f7fdf3c93210c58e59e566b1f73a9953b9990a/src/lib/styles/themes/dark.scss#L14-L17). 
Remove the incorrect comments.
=> Remove out-dated comments

src/lib/components/Tooltip.svelte, src/routes/(split)/components/tooltip/+page.md, src/tests/lib/components/Tooltip.spec.ts, src/tests/lib/components/TooltipTest.svelte
Currently the contents of the tooltip is specified as a text string.
We want to be able to show richer tooltips with styling.
Allow passing the tooltip content as a slot instead of just a `text` prop.
Note that with the `text` prop it's currently possible to disable the tooltip entirely by making the `text` prop empty or `undefined`.
When using the slot, there is currently no way to make the tooltip conditional.
This would require an additional boolean prop.
This might be useful but we'll add it when we need it.
=> Support rich content in tooltip

.github/workflows/checks.yml
This is the change analogous to https://github.com/dfinity/ic-js/pull/660 in ic-js.
When dependabot tries to make changes, CI fails because the personal access token can't be used on PRs made from forks.
See for example: https://github.com/dfinity/gix-components/pull/439
1. Check of the PR was made from a fork.
2. If so, don't use the token on checkout and fail instead of committing formatting changes if needed.
=> Do not use token on fork PRs

.github/workflows/checks.yml, src/lib/components/Tooltip.svelte
In https://github.com/dfinity/gix-components/pull/440 we checked if a PR came from a fork to determine if we could use the personal access token. But if the PR doesn't come from a fork, this doesn't guarantee that the token is available.
So we should just check for the presence of the token directly.
Instead of checking of the PR is from a fork, check if the `secrets.GIX_CREATE_PR_PAT` token is non-empty.
Token available, no formatting: https://github.com/dfinity/gix-components/actions/runs/9564874514/job/26366581872
Token available, with formatting: https://github.com/dfinity/gix-components/actions/runs/9565022869/job/26367048688
No token, no formatting: https://github.com/dfinity/gix-components/actions/runs/9564969586/job/26366881198?pr=442
No token, with formatting: …
=> Check for token instead of fork

src/lib/components/Popover.svelte, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
In https://github.com/dfinity/gix-components/pull/393 I added colors with the `--tooltip` prefix but these don't currently match the Tooltip colors in Figma. They match the Dropdown colors in Figma, but they are used for the `Popover` component. We also have Popup colors in Figma but no Popover colors.
In the [design](https://www.figma.com/design/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?node-id=1851-9872&t=YgFrTo6bb8sZXPJE-4) for the `Hide zero balances` feature, the popup uses the Dropdown colors. The implementation of the feature uses the `Popover` component. I'm not sure all of this is correct but now at least our CSS matches Figma regarding these colors.
I've also decided to just add all the Dropdown colors that are currently in Figma rather than only the ones we use.
1. …
=> Change tooltip colors to dropdown colors

src/lib/components/SplitContent.svelte, src/routes/(split)/components/split-content/+page.md, src/tests/lib/components/SplitContent.spec.ts, src/tests/lib/components/SplitContentTest.svelte
When switching between universes, the user would find themselves somewhere in the middle of the list. This issue went unnoticed before due to paginated loading, which resulted in the list being empty immediately after switching. However, with actionables now being preloaded, this has become a significant UX issue. 
The proposals are rendered inside the `SplitContent` component. To reset the scroll position without having to search through the DOM, we have added a `resetScrollPosition` function.
- new `resetScrollPosition` function.
No visual changes. Tested in nns-dapp.
=> Add resetScrollPosition function

.github/workflows/snapshots.yml
When updating the screenshots, the CLA can get stuck because CI doesn't run again.
The solution is to use the personal access token, similar to how we do when [formatting](https://github.com/dfinity/gix-components/blob/34247fb67b9fb0945e3d3ceee065a13a5e36723c/.github/workflows/checks.yml#L27).
Use the `secrets.GIX_CREATE_PR_PAT` in the snapshots workflow.
https://github.com/dfinity/gix-components/actions/runs/9581570545/job/26418670825
=> Use access token when updating screenshots

src/tests/lib/components/Tooltip.spec.ts
> Checking formatting...
> All matched files use Prettier code style!
> 
> /Users/daviddalbusco/projects/dfinity/gix-components/src/tests/lib/components/Tooltip.spec.ts
>   31:11  warning  'element' is assigned a value but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars
>   42:11  warning  'element' is assigned a value but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars
> 
> ✖ 2 problems (0 errors, 2 warnings)
- Remove two unused constants in a test.
=> chore: lint 'element' is assigned a value but never used in a test

src/routes/(split)/components/tooltip/+page.md
Ids must be unique within an HTML page. On the Tooltip showcase page, we are using multiple time the selement identitifier.
- Increment example identitfiers.
=> fix: Tooltip showcase page unique ids

.github/CODEOWNERS
We were requested by PRODSEC to enable Code Owners approval in the branch protections. Before doing so, we should add the NNS team to the CODEOWNERS file; otherwise, PRs will always require Gix team approval. This way, both NNS and Gix can approve PRs.
=> chore: add NNS team to CODEOWNERS

.github/workflows/checks.yml
We do not want the CI to pass when `npm run lint` detects warnings.
=> chore: do not accept lint warnings in CI

src/lib/styles/mixins/_effect.scss, src/lib/styles/mixins/_header.scss
The icon buttons that use the ripple-effect look good in the dark theme when focused or active (eg. after mouse down), but are too dim in the light theme. This happens because, in the light theme, the button’s background becomes dark when focused, and the icon color is also dark. To fix this and make the buttons clearly visible when clicked, this PR changes the text color of the button for affected states to provide more contrast with the background color.
- Added a new optional argument to the `ripple-effect` mixin to provide a custom text color (to avoid introducing a breaking change).
- Provided a custom text color for header buttons.
Note: the ripple effect remains without visual changes.
=> Improve clicked icon buttons visibility in light theme

e2e/tooltip.e2e.ts, src/lib/components/Tooltip.svelte, src/tests/lib/components/Tooltip.spec.ts, src/tests/lib/components/TooltipListTest.svelte
I noticed in the neurons table that when the order of the rows is changed, the tooltips are moved inside the `overflow: hidden` container and end up being cut off.
We move tooltips directly to the document body in `onMount` to make sure they are not cut off.
The solution I found is to move the tooltips again in `afterUpdate`.
Move tooltips to the document body in `afterUpdate` the same as in `onMount`.
1. Unit test added.
2. Checked that the unit test failed with `afterUpdate` commented out.
3. Updated e2e test because the tooltips are no longer guaranteed to be in the same order in the DOM as the tooltip targets.
4. Tested manually in an nns-dapp branch.
=> Move tooltip back to body in afterUpdate

src/lib/icons.ts, src/lib/icons/IconSort.svelte
We want to use the icon to access table sorting on mobile.
`IconSort.svelte`
=> Add IconSort

package-lock.json, package.json, src/tests/lib/components/Checkbox.spec.ts, src/tests/lib/components/Modal.spec.ts, src/tests/lib/components/Tooltip.spec.ts, src/tests/lib/components/TooltipListTest.svelte, src/tests/lib/components/WizardModal.spec.ts
Testing library [v5.0.0](https://github.com/testing-library/svelte-testing-library/releases/tag/v5.0.0) introduces a breaking change that changes the returned `container` position (see issue [#313](https://github.com/testing-library/svelte-testing-library/issues/313)).
- use `baseElement` instead of `container` when our test actually expect the body to perform search
- adapt `rerender` which are now promises and do not expect the `props` parameter
=> test: update and migrate testing-library v5

package.json
Npmjs displays a not well formatted description (see screenshot). I assume this happens because we do not have a `description` field in `package.json` and npmjs automatically fallbacks on the text provided in the README. It's an assumption but, in any case, it is worth to have such a field in the package.
- Add `"description": "A UI kit developed by the GIX team"` to `package.json`
=> chore: set about phrase as description in package.json

.github/workflows/checks.yml
This applies the changes from https://github.com/dfinity/snsdemo/pull/380 (in snsdemo) to gix-components.
`EndBug/add-and-commit` requires that the `checkout` action is called with `ref`, when used on a pull request, so it knows which branch to commit to. For some reason this was not required on older versions (7) of EndBug/add-and-commit.
In https://github.com/dfinity/snsdemo/pull/368 I changed to an earlier version of `EndBug/add-and-commit` to avoid having to pass `ref` to the `checkout` action, depending on whether the run is for a PR, to avoid having to have 4 different checkout steps.
I realized now that I only need to pass the token if I plan to make changes, so I can combine the checkout steps and still only have 2 while also using newer versions of `actions/checkout` and …
=> Combine access token and pull request checks in workflow

package-lock.json, package.json
We want to release a version of gix-cmp.
- Bump version number to `4.6.0`.
=> chore: bump version number

src/lib/icons.ts, src/lib/icons/IconAddCircle.svelte, src/lib/icons/IconBin.svelte, src/lib/icons/IconDots.svelte
For the import token feature, we need three new icons: a Dots icon for the context menu, a Bin icon for the remove button, and an AddCircle icon for the redesigned add button.
- Add and export the new icons.
=> New Dots, Bin and AddCircle icons

package-lock.json, package.json
To support agent-js v2 we also gonna need to bump gix-cmp.
This PR also clean up package-lock which was still referencing agent-js v0.15.5 and bump juno libs which were bumped to agent-js v2.0.0 as well.
```
npm rm @dfinity/utils
npm rm @junobuild/analytics @junobuild/config @junobuild/vite-plugin
npm i @dfinity/utils@next --save-peer
npm i @junobuild/analytics @junobuild/config @junobuild/vite-plugin -D
```
+ redo `*` for utils in package.json
=> build: agent-js v2

src/lib/components/Toast.svelte, src/lib/components/Toasts.svelte
Easily finding the components in the DOM for testing.
Add `data-tid` attributes in `Toasts` and `Toast` components.
N/A
=> Add test IDs to Toasts and Toast

src/lib/components/Menu.svelte
We want to merge the `MenuBackground` into the `Menu` component and make the `Menu` scrollable.
To limit the complexity of that PR, I want to first clean up the existing CSS.
The menu width is [specified as 200px](https://github.com/dfinity/gix-components/blob/8c5367f60e971b74508e62faefe48bfd4da107c7/src/lib/styles/global/variables.scss#L5), but the actual menu panel is `8px` or `16px` wider because of an extra padding or margin depending on the width of the viewport.
To simplify removing `MenuBackground`, we move the padding into `.inner` so that it's easier to center the logos.
And we use the same mechanism for large and small screens instead of using a margin in one case and a padding in the other case.
1. Split `padding` in the menu for large screens in `padding-top`, `padding-left`, …
=> Clean up menu padding

src/lib/components/Checkbox.svelte, src/tests/lib/components/Checkbox.spec.ts
Checkbox currently triggers keypress event on keypress and nnsChange event on click, eventhought it is disabled. Disabled input elements shouldn't trigger these events, if we need information related to disabled Checkbox events, those should be implemented separately.
Update Checkbox to not trigger events if disabled.
no change
=> Disable triggering events if checkbox is disabled

src/lib/stores/menu.store.ts, src/tests/lib/stores/menu.store.spec.ts
Make it easier to write robust unit tests.
Add `resetForTesting` to `menuStore` which sets the value to `Menu.EXPANDED`.
N/A
=> Add resetForTesting to menuStore

package.json, src/tests/lib/components/Popover.spec.ts, src/tests/lib/utils/tooltip.utils.spec.ts
In https://github.com/dfinity/gix-components/pull/508 I had to add a missing type declaration.
This wasn't caught earlier because test are not compiled.
1. Compile tests when running `npm run test` by adding `tsc --noEmit -p ./tsconfig.spec.json &&`.
2. Fix existing issues caught by the compiler.
1. Make rectangles of type `DOMRect` by adding a `toJSON` method.
2. Declare type of params of `createTargetAndTooltipRects`.
3. Fix `backdrop might be undefined` because the compiler doesn't understand it's not possible after `expect(backdrop).not.toBeNull();`
N/A
=> Compile test code

src/lib/components/Menu.svelte, vite.config.js
Similar to what was done for OISY repo with PR #https://github.com/dfinity/oisy-wallet/pull/2441, we resolve the warnings
Source: https://stackoverflow.com/a/79003101/5404186
- Use modern compiler for `sass`
- Move the sub-classes after the class declarations.
=> build: migrate to scss modern-compiler

.github/workflows/checks.yml, .github/workflows/next.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml
Bumping the `actions/checkout` to version 4, since we were receiving warnings.
=> ci: bump checkout action

src/lib/icons/IconThumbDown.svelte, src/lib/icons/IconThumbUp.svelte
Replace original google font icons with a Dfinity version.
- Replaces svgs 
- Adds size prop to make them responsive.
=> NNS1-3435: Updates thumbs-up and thumbs-down icons

src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
A new theme requires a new light variable to be used for negative emphasis connotation.
-  A new semantic color variable has been added to the themes.
=> NNS1-3435: adds a new semantic color variable to the themes

src/lib/styles/global/colors.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Fix minor color mismatches
1. The variable --disable-contrast-rgb doesn’t match --disable-contrast.
2. When the new dark theme was introduced, the light theme was not updated. However, some colors, such as those for the tooltip, are derived from the opposite theme and need to be updated as well:
- Update --tertiary to be blue instead of violet.
- Update the light theme’s tooltip to suit the new dark theme.
3. Update the dark theme’s tooltip colors to match the new tooltip colors.
Note: All the changes were visually reviewed with the designer.
| Before | To |
|--------|--------|
| <img width="365" alt="image" src="https://github.com/user-attachments/assets/dd6ff3ab-092a-4229-b0cf-f985f5e43259"> | <img width="301" alt="image" src="https://github.com/user-attachments/assets/3139aa86-853d-4a66 …
=> Fix minor color mismatches

src/lib/icons.ts, src/lib/icons/IconArrowsSwitch.svelte
This icon is needed for the USD values design to switch the USD and ICP amounts.
1. Add `src/lib/icons/IconArrowsSwitch.svelte`
=> Add icon ArrowsSwitch

src/routes/(page)/browser/+page.svelte
Fix an error - that blocks the build - detected when migrating to Svelte v5 in #541:
> error during build:
[vite-plugin-svelte] [plugin vite-plugin-svelte] src/routes/(page)/browser/+page.svelte (27:2): src/routes/(page)/browser/+page.svelte:27:2 `<tr>` cannot be a child of `<table>`. `<table>` only allows these children: `<caption>`, `<colgroup>`, `<tbody>`, `<thead>`, `<tfoot>`, `<style>`, `<script>`, `<template>`. The browser will 'repair' the HTML (by moving, removing, or inserting elements) which breaks Svelte's assumptions about the structure of your components
- Add `tbody`
=> fix: <tr> cannot be a child of <table>

src/lib/components/Backdrop.svelte, src/lib/components/ProgressBar.svelte, src/lib/components/ProgressSteps.svelte, src/lib/components/QRCode.svelte, src/lib/components/QRCodeReader.svelte, src/lib/components/Segment.svelte, src/lib/components/Toggle.svelte, src/tests/lib/components/ContentTest.svelte, src/tests/lib/components/IslandTest.svelte, src/tests/lib/components/MenuItemTest.svelte, src/tests/lib/components/MenuTest.svelte, src/tests/lib/components/NavTest.svelte, src/tests/lib/components/PopoverTest.svelte, src/tests/lib/components/SplitBlockTest.svelte, src/tests/lib/components/SplitContentTest.svelte, src/tests/lib/components/SplitPaneTest.svelte, src/tests/lib/components/StretchPaneTest.svelte, src/tests/lib/components/TestIdWrapperTest.svelte, src/tests/lib/components/ToolbarTest.svelte
Fix a linter error reported by latest Svelte v5 linter in https://github.com/dfinity/gix-components/pull/541:
> Self-closing HTML tags for non-void elements are ambiguous — use `<div ...></div>` rather than `<div ... />`(element_invalid_self_closing_tag)  svelte/valid-compile
- Replace self closing tags. e.g. `<div />` -> `<div></div>`
=> fix: Self-closing HTML tags

src/lib/components/MenuItem.svelte
Fix an error - that blocks the build - detected when migrating to Svelte v5 in #541:
> error during build:
[vite-plugin-svelte] [plugin vite-plugin-svelte] src/lib/components/MenuItem.svelte (73:10): src/lib/components/MenuItem.svelte:73:10 Nesting selectors can only be used inside a rule or as the first selector inside a lone `:global(...)`
It seems that the rule is actually unused / not applied. Therefore I remove it.
- Remove nested CSS global rule.
=> fix: nesting selectors in menu item

package.json
I compared our setup with a sample Svelte app and noticed that the `package.json` contained a `sideEffects` field. While we do not necesseraly needs it, according [documentation](https://svelte.dev/docs/kit/packaging#Anatomy-of-a-package.json-sideEffects), it's advised to add it.
- Specify a `sideEffect` for `css` in `package.json` to help bundlers tree shake those files when the lib is consumed.
=> chore: add sideEffects to package.json

vite.config.js
I'm not sure we realy needs it but Svelte is advising to tell Vitest to use the `browser` entry points in `package.json` for the configuration of the test. Since I'm reviewing the configuration of the repo while migrating to Svelte v5, I think it's good to align this as well.
Source: https://svelte.dev/docs/svelte/testing#Unit-and-integration-testing-using-Vitest-Component-testing
- Set `condition` equals to `browser` in `resolve` for Vitest.
=> chore: tell Vitest to use the `browser` entry points in `package.json`

.github/workflows/checks.yml
This updates the comment with the currently correct information.
No code changes, just updating a comment.
=> chore(): update comment

src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
To solve the low contrast of the banners in cards and standardize their appearance, a new color theme variable has been added.
- Added `--banner-background` to both themes.
| Before | After |
|--------|--------|
| <img width="792" alt="image" src="https://github.com/user-attachments/assets/cae9911b-b076-44de-b1dc-0ab9643b391d" /> | <img width="786" alt="image" src="https://github.com/user-attachments/assets/fe88b1a8-3721-4445-9b99-064796e2d050" /> |
| <img width="777" alt="image" src="https://github.com/user-attachments/assets/6583d802-b434-4a9e-ab19-e73f882cf454" /> | <img width="779" alt="image" src="https://github.com/user-attachments/assets/931df786-fe04-4b35-9cd7-e8b25ec8368e" /> | 
| <img width="1176" alt="image" src="https://github.com/user-attachments/assets/7cb46733-8d86-4442-8175 …
=> Add banner bg variable

.github/workflows/checks.yml, src/lib/components/Section.svelte
On the neuron details page, the voting power block needs to be displayed within a collapsible section. To achieve this, we can’t use the section’s title slot and must instead rely on a custom title (within the KeyValuePairInfo) placed in the section’s description block. Currently, if the title slot is left empty, an extra margin is added, which is undesirable.
- Do not add the margin, when no title provided.
- Tested locally against nns-dapp.
=> Avoid margin when no title

src/lib/components/Segment.svelte, vitest.setup.ts
Tests in #563 were failing. After debugging, I figured out that the potential display issue actually already existed on the main branch. Specifically, since the segment buttons have no fixed width, depending on the rendering, it's possible that on mount, the buttons are not yet fully rendered—meaning they haven't occupied their full width yet—resulting in the indicator position not being accurately calculated. Similarly, the buttons might be rendered, but the font could take time to load, causing the indicator position to be calculated with the fallback font instead of the final one. Additionally, if the language is changed at runtime, it might result in a change in the buttons' length.
Long story short, observing the size of the container and repositioning the indicator when the size …
=> feat: observe resize segment for better indicator display

src/lib/components/InfiniteScroll.svelte
As I discovered in Juno (PR [#1092](https://github.com/junobuild/juno/pull/1092)), where I have a similar infinite scroll component to the one in Gix-cmp, the `InfiniteScroll` component no longer works after the migration to Svelte v5. The root cause of the issue is the following breaking change in Svelte:
> beforeUpdate/afterUpdate no longer run when the component contains a and its content is updated.
https://svelte.dev/docs/svelte/v5-migration-guide#Other-breaking-changes-beforeUpdate-afterUpdate-changes
Currently, we observe changes on the container to disconnect and reconnect the intersection observer. However, since there won't be any updates anymore, the observer will not reconnect, and the component will not fetch any new data after the first scroll event.
This issue is confirmed …
=> feat: use an element target in infinite scroll

src/lib/components/Input.svelte, src/tests/lib/components/Input.spec.ts
There are two reactive statements that define `step` and `autocomplete`.
For step, they are identical, so we can remove them.
For `autocomplete`, one of the two ignores the prop `autocomplete` for currency input type. I think that the objective is to have this ONLY for type `number`.
=> chore: remove redundant statement for autocomplete in Input

src/tests/lib/components/InputElementTest.svelte
The linter found some issues with the `InputElementTest` component in Svelte 5. To prevent unexpected behavior, we want to address these issues.
- resolves linter issues
=> feat: fixes linter issues

src/lib/directives/transition.directives.ts
Few params types were not correctly inherited in #573.
- Use `FlyParams` for "fly" and `ScaleParams` for "scale" instead of `FadeParams`.
=> fix: transitions wrappers params types

src/lib/directives/transition.directives.ts
Provide a wrapper for the "slide" transition, similarly as those which were provided in #573.
Needed in OISY for Svelte v5 - i.e. looks like we will have to use those wrappers in consuming dApps as well.
The PR also 
- Add `testSafeSlide`.
=> feat: transition slide wrapper and params

src/lib/styles/mixins/_layout.scss
We receive some warnings from SASS new version:
```bash
DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
┌──> src/lib/styles/mixins/_layout.scss
23 │     box-sizing: border-box;
│     ^^^^^^^^^^^^^^^^^^^^^^ declaration
╵
┌──> src/lib/styles/mixins/_media.scss
17 │ ┌     @media (min-width: $breakpoint-medium) {
18 │ │       @content;
19 │ │     }
│ └─── nested rule
╵
src/lib/styles/mixins/_layout.scss 23:3                          content() …
```
=> refactor: solve SASS warnings

svelte.config.js
We can use the version to setup build reproducibility and save few cycles when deploying to `gix.design`.
- Setup version as we do in OISY or NNS Dapp or Juno
=> build: use version to setup build reproducibility

src/docs/constants/docs.constants.ts, src/lib/components.ts, src/lib/components/SystemThemeListener.svelte, src/lib/stores/theme.store.ts, src/lib/utils/theme.utils.ts, src/routes/(split)/components/system-theme-listener/+page.md, src/tests/lib/components/SystemThemeListener.spec.ts
A component that listens to changes in the users system/OS theme, fully integrated with the existing theme system by default.
- Added component
- Added docs route and page
- Added export to expose it
This component doesnt render anything.
=> feat: System Theme Listener component

src/tests/lib/components/SystemThemeListener.spec.ts
Using `$on` is incompatible with Svelte v5.
- Update theme listener test to use the existing `events` property of the render utils.
=> test: use events instead of $on for theme listener

src/lib/components.ts, src/lib/components/ChipGroup.svelte, src/lib/index.ts, src/lib/types/chip-group.ts, src/routes/(split)/components/chip-group/+page.md
To make the ChipData type available, it needs to be explicitly exported.
- Rename ChipData to ChipGroupItem.
- Move it to a separate file under types.
- Explicitly export it.
No changes.
=> Export type ChipGroupItem

src/lib/components/Input.svelte, src/routes/(split)/components/input/+page.md
We want to display the USD value in transaction forms within the nns-dapp. To achieve this, we need to extend the input to include a "bottom" section with custom styles.
Example from the nns-dapp:
- Expose a new slot in the `Input` field
=> feat(ui): add bottom slot to input component

package-lock.json, package.json
We want to release a minor version before merging and release a major version for Svelte v5.
- Bump `v5.2.0`
=> chore: bump version number for release

package-lock.json, package.json
We want to release a major version to rollout the migration to Svelte v5 (#548).
- Bump `v6.0.0`
=> chore: bump version number for releasing Svelte v5

package-lock.json, package.json
We are not affected but, for the state of the art, let's bump vite to resolve https://github.com/advisories/GHSA-x574-m823-4x7w
This version of vite is already used in OISY and NNS dapp. ✅
- Bump vite v6.2.3
=> build: bump vite (CVE-2025-30208)

.github/workflows/checks.yml, .github/workflows/next.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml
Gix uses an Ubuntu runner that will be deprecated on April 1st. A Slack [message](https://dfinity.slack.com/archives/CH4CADCJX/p1740558752499169) pointed to some repositories, but gix-components was overlooked.
We have some issues in the pipeline with open PRs. For example: https://github.com/dfinity/gix-components/actions/runs/14200871834
- Upgraded the version to `ubuntu-22.04`.
- CI should pass
Not necessary.
=> chore(ci): upgrade github actions runner to ubuntu-22.04

package-lock.json, package.json
Another week, anoter security issue in vite. Similarly to latest incident (#610), we are not affected but, for the state of the art, let's bump vite to resolve [CVE-2025-31125](https://github.com/advisories/GHSA-4r4m-qw57-chr8).
- Bump vite v6.2.4
=> build: bump vite (CVE-2025-31125)

src/lib/icons/IconLaunchpad.svelte, src/lib/icons/IconTokens.svelte
The nns-dapp wants to use the `IconLaunchpad` and `IconTokens` in different sizes. This PR introduces a `size` prop, similar to the approach used for other icons. To maintain backward compatibility, it does not use `DEFAULT_ICON_SIZE`; instead, it employs a local variable to set the size to 40 px.
- Expose the new `size` prop in `IconLaunchpad` and `IconTokens`
Not necessary.
=> feat(icons): add size prop for launchpad and token icons

package-lock.json, package.json
Another week, anoter security issue in vite. Similarly to latest incidents (#610 and #614), we are not affected but, for the state of the art, let's bump vite to resolve [CVE-2025-31486](https://github.com/advisories/GHSA-xcj6-pq6g-qj4x).
- Bump vite v6.2.5
- Bumo related dev dependencies
=> build: bump vite (CVE-2025-31486)

package-lock.json, package.json
Another day, anoter security issue in vite. Similarly to latest incidents (#610, #614 and #617), we are not affected but, for the state of the art, let's bump vite to resolve [GHSA-356w-63v5-8wf4](https://github.com/vitejs/vite/security/advisories/GHSA-356w-63v5-8wf4).
- Bump vite v6.2.6
=> build: bump vite (GHSA-356w-63v5-8wf4)

package-lock.json, package.json
The upgrade to Svelte 5 broke the [icons page](https://gix.design/icons) due to a regression issue caused by Svelte Kit deserializing the payload from the backend file.
Svelte Kit has addressed this issue in the [latest version](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%402.20.7).
- Upgrade SvelteKit to the latest version.
=> fix(deps): upgrade sveltekit to resolve icons page serialization

src/lib/icons.ts, src/lib/icons/IconEyeOpen.svelte
The nns-dapp needs a new icon to be displayed in a `Highlight` component.
- Adds new icon
=> feat(icons): add EyeOpen component

src/lib/components/Input.svelte, src/routes/(split)/components/input/+page.md, src/tests/lib/components/Input.svelte.spec.ts
In OISY, the autofocus is used several times with a custom implementation. To be able to use the browsers implementation of autofocus, this PR exposes the `autofocus` property.
Compare: https://github.com/dfinity/oisy-wallet/pull/5901
- Exposes the `autofocus` property
=> feat(input): Adds autofocus property to input component

src/lib/components/InfiniteScroll.svelte, src/routes/(split)/components/infinite-scroll/+page.md, src/tests/lib/components/InfiniteScroll.spec.ts, src/tests/lib/components/InfiniteScrollTest.svelte
We start the Svelte 5 migration with component InfiniteScroll, that is more prone to cause incompatibility issues with projects that already use Svelte 5 components.
Note that I am explicitly set the prop `children` as non-optional, since I imagine that this component shall be used only with children.
BREAKING CHANGE: the interface changes.
Credits to @peterpeterparker from [Juno's component `InfiniteScroll`](https://github.com/junobuild/juno/blob/cd44adace1ff530cc8c2f544bfbc77b25aace88a/src/frontend/src/lib/components/ui/InfiniteScroll.svelte#L5)
=> feat!: migrating `InfiniteScroll` to Svelte 5

src/lib/index.ts, src/lib/types/event-modifiers.ts, src/lib/utils/event-modifiers.utils.ts, src/tests/lib/utils/StopPropagationTest.svelte, src/tests/lib/utils/event-modifiers.utils.spec.ts
According to [Svelte 5 documentation](https://svelte.dev/docs/svelte/v5-migration-guide#Event-changes-Event-modifiers), with the migration, the event modifiers are deprecated and should be replaced by functions that have the same scope. For example, instead of:
```svelte
<button on:click|preventDefault={handler}>...</button>
```
One should do
```svelte
<script>
function preventDefault(fn) {
return function (event) {
event.preventDefault();
fn.call(this, event);
};
}
</script>
<button onclick={once(preventDefault(handler))}>...</button>
```
In this PR we create the `stopPropagation` util, to help with the migration (it will be used in other PR, like https://github.com/dfinity/gix-components/pull/631).
- Creating a new type for event handlers.
- Creating new util for stop propagation, based …
=> feat: Util for event modifier `stopPropagation`

.github/workflows/deploy.yaml, juno.config.ts, package-lock.json, package.json
The deploy to Juno script was still using Node v18. The action also supports new cool features, such as supporting pre/post deploy scripts in the configuration. So this PR update script and config to latest standards.
=> chore: update CI deploy to Juno to latest

.github/workflows/checks.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml
We want to use the "prepare" action recently introduced (cloned from ic-js and other repo) to setup Node LTS and install dependencies in every CI jobs.
=> chore: use CI prepare action

e2e/tooltip.e2e.ts
The tootltip e2e test are flaky. This PR tries to relax the screenshot comparison to resolve the issue.
CI tests in error: https://github.com/dfinity/gix-components/actions/runs/15105337805/job/42452977219?pr=643
=> test: flaky tooltip e2e test

src/lib/icons.ts, src/lib/icons/IconEyeClosed.svelte
Introduces a new icon, `IconEyeClosed`, for use in the nns-dapp during the hide/show balance flow.
- Adds new icon
=> feat(icons): add eye-closed icon 

src/lib/components/Content.svelte, src/routes/(page)/+layout.svelte, src/routes/(split)/components/content/+page.md, src/tests/lib/components/ContentTest.svelte
Migrating component `Content` button to Svelte 5.
The interface changes:
- The slots `title` and `toolbar-end` are migrated to Snippets.
- No event `nnsBack` bubbling up anymore, use the prop `onBack` that receives the callback function.
- The prop `back` is deprecated, the nullish check of `onBack` callback will replace it.
=> feat!: Migrate `Content` to Svelte 5

src/lib/components/SplitContent.svelte, src/routes/(split)/+layout.svelte, src/routes/(split)/components/split-content/+page.md, src/tests/lib/components/SplitContentTest.svelte
Migrating component `SplitContent` button to Svelte 5.
The interface changes:
- The slots `title`, `toolbar-end`, `start` and `end` are migrated to Snippets.
- No event `nnsBack` bubbling up anymore, use the prop `onBack` that receives the callback function.
- The prop `back` is deprecated, the nullish check of `onBack` callback will replace it.
=> feat!: Migrate `SplitContent` to Svelte 5

src/lib/components/Content.svelte, src/lib/components/Header.svelte, src/lib/components/SplitContent.svelte
Migrating component `Header` button to Svelte 5.
The interface changes:
- The slots `title` and `toolbar-end` are migrated to Snippets.
- No event `nnsBack` bubbling up anymore, use the prop `onBack` that receives the callback function.
- The prop `back` is deprecated, the nullish check of `onBack` callback will replace it.
=> feat: Migrate `Header` to Svelte 5

src/lib/components/ExternalLink.svelte
Migrating component `ExternalLink` to Svelte 5.
=> feat: Migrate component `ExternalLink` to Svelte 5

src/lib/icons/IconCheck.svelte, src/lib/icons/IconCheckCircle.svelte, src/lib/icons/IconClock.svelte
Migrating icons to Svelte 5. In this fifth part we focus on icons with the same type of parameters, to facilitate the review.
=> feat: Bulk-migrate icons to Svelte 5 - part 5

src/lib/icons/IconLaunchpad.svelte, src/lib/icons/IconTokens.svelte
Migrating icons to Svelte 5. In this third part we focus on icons with the same type of parameters, to facilitate the review.
=> feat: Bulk-migrate icons to Svelte 5 - part 3

src/lib/components/TestIdWrapper.svelte, src/tests/lib/components/TestIdWrapperTest.svelte
Migrating component `TestIdWrapper` to Svelte 5.
=> feat: Migrate component `TestIdWrapper` to Svelte 5

src/lib/types/event-modifiers.ts, src/lib/utils/event-modifiers.utils.ts, src/routes/(page)/utility-functions/+page.md, src/tests/lib/utils/event-modifiers.utils.spec.ts
We should pass the event to the event modifiers callback. That is what is suggested in the official documentation too (see https://svelte.dev/docs/svelte/v5-migration-guide#Event-changes-Event-modifiers), but in general, it makes sense. Especially, if we use the modifiers concatenated.
- Create simplified type for event parameter.
- Pass the event to the call back function in both exiting modifiers.
- Removing optionality of events, since it is not necessary.
Current tests were adapted to test this new change. The unchanged tests must work as usual.
=> fix: Pass event to callback of event modifiers

src/lib/components/Modal.svelte
The current modal centering uses a transform-based hack which complicates responsive adjustments and theming. Switching to a flex‐based centering approach will simplify the CSS, make the overlay consistently centered across different viewport sizes, and improve maintainability.
Modal container
Removed: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);
Added display: flex; justify-content: center; align-items: center; on the modal wrapper
Verified centering on desktop and mobile viewports in Chrome, Firefox, Safari, and Edge
Tested with varying modal content heights (short alerts vs. long forms)
Confirmed scroll behavior and that focus management still works
=> feat(frontend): change the modal centalization style

src/lib/components/Collapsible.svelte
The `Collapsible` component renders `TestIdWrapper`. This last component required a non-nullish `testId` (for obvious reasons). So, since this seems to be the intention of the code, we default the `testId` to a value.
=> fix: Default testId for `Collapsible` component

e2e/progress-steps.e2e.ts
A new step was included in the Progress step component showcase, but that means that we should wait slightly more for the animation to finish before taking the snapshot, to be sure and avoid flakiness.
=> fix: Flaky E2E test for Progress steps
