.github/workflows/checks.yml, README.md, scripts/fmt-sh, svelte.config.js, vite.config.js
Format, lint, build and test in CI.
Copied and adapted from ic-js.
=> build: ci formatting and checks

src/app.html, src/routes/__layout.svelte, src/routes/index.svelte, src/routes/start.md
GIX not Gix and add note about svelte.
=> docs: gix in capital letter and svelte

README.md
=> docs: display deployed url in readme

src/docs/components/DocsIcon.svelte, src/docs/styles/docs-global.scss
Improve code and icons display on docs website with contrasting colors.
=> docs: constrast color for website

src/lib/components/Card.svelte
Add meta class to Card component (more precise selectors)
Card `div` -> `.meta`
=> chore: add meta class to Card component (more precise selectors)

src/lib/styles/global/utility-classes.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Mischa's review.
- adjust cell gap spacing
- introduce line color
=> style: line color and cell gap

src/lib/styles/global/grid.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Small improvements noticed while tweaking recent proposal details new ui.
- we do not need grid `content-e` and `content-f`
- grid first row height set to `max-content` to avoid too much spacing
- update new json colors
=> style: improvements for proposals new design

src/app.html, src/lib/components/BottomSheet.svelte
Respect safe area of iOS bottom inset for bottom sheet.
=> style: bottom sheet safe area

src/lib/styles/global/layout.scss, src/lib/styles/global/variables.scss
The header can remains with an initial z-index to solve various stacking issue.
=> style: inherit header z-index and push modal z-index

src/lib/styles/global/button.scss, src/lib/styles/themes/themed-button.scss, src/routes/resources/+page.svelte, src/routes/utility-classes/buttons/+page.md
Review buttons style according figma design.
- lib: buttons padding, border, hover, focus etc. according figma
- lib: `disabled` is the same for all buttons
- lib: `.small` button style deprecated
- docs: update buttons showcase with more flavors
=> style: review buttons style according figma design

.github/workflows/publish.yml
Publish `@dfinity/gix-components` to npm on release.
- new github actions that follows `ic-js` pattern
=> build: publish to npm on release

src/lib/styles/global/button.scss
Fix button width when enabling and disabling `primary`
=> style: fix button width when enabling and disabling primary

src/docs/styles/docs-global.scss, src/lib/components/MenuItem.svelte, src/lib/styles/global/link.scss, src/lib/styles/global/theme.scss, src/lib/styles/global/variables.scss
Review link according new design and fix size issue.
- fix size issue in modal by inheriting the size
- review design, it should be `primary` color
- smoother color changes in menu items
=> style: review link design

src/lib/styles/global/modal.scss
=> style: align modal toolbar buttons end

src/lib/styles/global/variables.scss
=> style: fix modal height in mobile landscape

src/lib/components.ts, src/lib/components/WizardModal.svelte, src/lib/components/WizardTransition.svelte, src/lib/index.ts, src/lib/stores/wizard.state.ts, src/lib/types/wizard.ts, src/lib/utils/wizard.utils.ts, src/routes/components/+page.svelte, src/routes/components/wizard-modal/+page.md, src/tests/stores/wizard.state.spec.ts
Move wizard modal from NNS-dapp.
=> feat: wizard modal

src/tests/components/Popover.spec.ts, src/tests/components/PopoverTest.svelte
=> Inclusion of Popover Test spec

src/lib/components/Menu.svelte, src/lib/components/SplitPane.svelte
Do now wait on JavaScript to move the content once the menu is displayed but amend the fact that the menu will use space.
=> style: fix glitchy menu appearance on xtra large screen

src/lib/components.ts, src/lib/components/KeyValuePair.svelte, src/lib/components/KeyValuePairInfo.svelte, src/lib/components/Value.svelte, src/routes/components/+page.svelte, src/routes/components/key-value-info/+page.md, src/routes/components/key-value/+page.md, src/routes/components/value/+page.md, src/tests/lib/components/KeyValuePair.spec.ts, src/tests/lib/components/KeyValuePairInfo.spec.ts, src/tests/lib/components/KeyValuePairInfoTest.svelte, src/tests/lib/components/KeyValuePairTest.svelte
Move `Value`, `KeyValuePair` and `KeyValuePairInfo` from NNS-dapp.
=> feat: key value pair

package-lock.json, package.json
Release a version with _blank and menu improvements before bumping to v2
=> chore: release v1.1.0

src/app.html, src/docs/styles/docs-global.scss, static/manifest.webmanifest
Default dark theme color as new card background color (not the color of last week).
Note: only apply on the documentation
=> style: default theme color

src/docs/plugins/slug.plugin.ts, src/lib/styles/mixins/_card.scss, src/routes/resources/+page.svelte
- remove unused style (overriden by mixin)
- update figma design constant short url
- remove invalid icon attribute for showcase
=> chore: house keeping

src/lib/components/KeyValuePairInfo.svelte, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
=> style: line colors

src/lib/components/MenuBackground.svelte, src/lib/components/MenuItem.svelte
=> style: background footer z-index

src/lib/styles/global/button.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Design has updated the colors of the primary and secondary buttons.
- review primary and secondary buttons colors
- add a filter for success and warning hover effect
=> style: review button colors according updated design

package-lock.json, package.json
Release a new version of the library.
- bump next version `v2.1.0`
- add peer dependency as suggested by SvelteKit (following recent upgrade of the dependencies)
=> build: release v2.1.0

src/lib/components/Modal.svelte, src/lib/components/Toast.svelte, src/lib/styles/global/button.scss, src/lib/styles/mixins/_overlay.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
I noticed that the "color" of the secondary button was not the contrast one in the Figma file defined by the designer.
This PR tweaks the secondary button to be closer to what they have in mind.
=> style: secondary button

src/lib/components/Menu.svelte, src/lib/components/MenuBackground.svelte, src/lib/components/Nav.svelte
Improve spacing for split content design applied in NNS-dapp.
=> style: spacing for split content

src/lib/components/StretchPane.svelte, src/lib/constants/constants.ts
Needed for login screen changes requested.
=> feat: expose constant for extra large breakpoint in JS

src/lib/icons/IconError.svelte, src/lib/icons/IconHistoryToggleOff.svelte, src/lib/icons/IconLogin.svelte, src/lib/icons/IconSouth.svelte, src/lib/icons/IconSubdirectory.svelte, src/lib/icons/IconWarning.svelte
Double check that all icons have a source comment.
=> docs: cleanup source

.github/workflows/nightly.yml, .github/workflows/publish.yml, .gitignore, package-lock.json, package.json
There are breaking changes in the way things need to be packaged in last SvelteKit release.
=> build: sveltekit package upgrade

package-lock.json, package.json, scripts/update-version.mjs
Fix nightly version script that modify the version in package.json and bump version number to make a release
=> build: nightly and version

src/lib/icons.ts, src/lib/icons/IconSettings.svelte
=> feat: icon settings

src/lib/components/Spinner.svelte, src/lib/icons/IconInfo.svelte, src/routes/(split)/components/spinner/+page.md
Add tiny size to the display option of the spinner.
=> feat: tiny spinner

src/lib/components/Modal.svelte, src/lib/components/QRCode.svelte, src/routes/(split)/components/popover/+page.md
- remove unused styles
- remove role on canvas ( build -> `<canvas> cannot have role 'img'`)
=> style: remove unused selector and role

src/lib/icons/IconSouth.svelte
=> style: custom icon south

src/lib/styles/themes/light.scss
Set `--description-color` light mode vaue as requested by Artem.
=> style: update light mode --description-color

src/lib/components/Modal.svelte, src/lib/components/QRCodeReader.svelte
- add a css variable for the content `overflow` property of the modal
=> style: modal style overflow CSS variable

package-lock.json, package.json
Solve [build issue](https://github.com/dfinity/gix-components/actions/runs/4752176407/jobs/8442201750) with `provenance`.
> npm ERR! code E422
>npm ERR! 422 Unprocessable Entity - PUT https://registry.npmjs.org/@dfinity%2fgix-components - Failed to validate repository information: package.json: "repository.url" is "undefined", expected to match "git+https://github.com/dfinity/gix-components" from provenance
=> build: add repository info and license to package.json

src/lib/styles/global/utility-classes.scss, src/routes/(page)/utility-classes/+page.svelte, src/routes/(page)/utility-classes/numbers/+page.md
Add a number utility class to display numbers monospaced.
=> style: number utility class

src/tests/tsconfig.json, tsconfig.spec.json
Webstorm does not resolved `$lib` for tests.
=> build: fix tsconfig for test

src/lib/icons.ts
Forgot to expose the new icon introduced with PR https://github.com/dfinity/gix-components/pull/224.
=> build: expose new icon sync

src/lib/icons/IconSync.svelte
Artem draw an icon `Sync` that matches better the dapp design.
=> feat: icon Sync designed by Artem

src/routes/(page)/resources/+page.svelte
Add new UI/UX links (concept) in the resources.
=> docs: new Figma links

src/tests/lib/components/Content.spec.ts, src/tests/lib/components/SplitContent.spec.ts, src/tests/lib/components/ToastsTest.svelte, src/tests/lib/stores/toasts.store.spec.ts
Use $lib path instead of related in tests.
=> chore: use $lib path

src/lib/stores/busy.store.ts, src/tests/lib/components/BusyScreen.spec.ts
Add types to busy store and a reset function for test purpose.
=> feat: busy store type and reset

src/lib/components/Checkbox.svelte
Add test id to the checkbox component.
- data-tid="checkbox-component"
=> Add "checkbox-component" to Checkbox

src/lib/components/Checkbox.svelte
Checkbox `testId` param
- new param
=> add dynamic test id for Checkbox

src/lib/icons.ts
New icon is not exported and can't be used.
* Add new icon to export list.
No UI changes
=> Chore: Export new icon

src/lib/components/Card.svelte, src/lib/styles/global/button.scss, src/lib/styles/global/grid.scss
Aligment issues due to the introduction of the card links.
- update style to align cards
after
=> fix: align link card and button card

package-lock.json, package.json
=> build: release v2.7.0

package-lock.json, package.json
I've made few fix and improvements in Juno's analytics this evening. Bumping the library provides those enhancement for the showcase.
=> build: bump juno analytics lib

src/lib/components/QRCodeReader.svelte
Currently if the QRCodeReader component is destroyed before the scanner is started, it fails to stop the scanner and then the camera is turned on and stays on until the page is reloaded.
1. Don't try to stop the scanner if it's not started.
2. Stop the scanner after starting if the component is destroyed.
There is still an error if they component is destroyed because the reader is started but at least the camera won't remain on.
```
html5-qrcode.js?v=a11cfc36:27301 Uncaught (in promise) TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
at html5-qrcode.js?v=a11cfc36:27301:23
at async QRCodeReader.svelte?t=1693908189579:105:4
qr-code-reader:1 Uncaught (in promise) DOMException: The play() request was interrupted because the media was removed from the …
```
=> Stop QRCodeReader if component destroyed before started

package-lock.json, package.json
Bump vitest and vite-plugin-svelte (because of issue https://github.com/dfinity/gix-components/pull/300#issuecomment-1744910316 which was solved in https://github.com/sveltejs/vite-plugin-svelte/issues/710#issuecomment-1672661958).
=> build: bump vitest

package-lock.json, package.json
Release a version v2.8.0 before we jump to v3 with Svelte v4.
=> build: release v2.8.0

src/lib/styles/global.scss, src/lib/styles/global/selection.scss
Apps are more fun when text selection fits the design colors.
=> style: selection color

src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
We are transitioning to a new set of colors defined in Figma. Not all have been exposed yet. We do it gradually.
In this PR, I expose only the colors needed for the tokens page.
* Add colors to light and dark themes.
No new components, and the new colors are not yet used in any of the current components.
=> Chore: New colors for Tokens page

src/lib/icons.ts, src/lib/icons/IconCollapseAll.svelte
Add icon for collapse all action.
- `IconCollapseAll` component
=> Add collapse all button

src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Use CSS variables for the colors of the new table in the Tokens page.
In this PR, add variables in the dark and light themes.
* Add four new CSS variables for colors in light and dark themes.
No changes.
=> Feat: Add new table colors

package-lock.json, package.json
Open next version before integrating last version in NNS dapp.
=> build: open next version v3.2.0

package-lock.json, package.json
Both light and dark mode theme have been reviewed and their color differences is quite predominant therefore we think it is worth releasing those as a major version.
- bump version v4 for release
=> build: release v4

src/lib/icons/IconQRCodeScanner.svelte
Change the IconQRCodeScanner.
Requested by design.
* Changes in IconQRCodeScanner.
This is how it looks in NNS Dapp
=> Feat: Change IconQRCodeScanner

src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Change theme colors requested by design.
* Change some light and dark theme colors.
Before Input on focus:
After Input on focus:
Before disabled card:
After disabled card:
=> Fix: Theme colors

src/lib/components/Copy.svelte
To test if the component is present in the DOM.
Added `data-tid` attribute to `Copy` component.
N/A
=> Add test ID to Copy component

package-lock.json, package.json
There was quite few improvements since last release, therefore I want to publish a new version. 
- bump version to 4.1.0
=> chore: bump to release next version

src/lib/styles/global/button.scss, src/lib/styles/global/variables.scss, src/lib/styles/mixins/_button.scss
Create a `--button-border-size` css variable to be used for button size adjustments.
- new global css var `--button-border-size`
=> style: add --button-border-size var

src/lib/components/Toggle.svelte, src/routes/(split)/components/toggle/+page.md, src/tests/lib/components/Toggle.spec.ts
I need disabled toggle in Oisy.
- add an option to disable `Toggle`
Required for this feature:
=> feat: toggle disable

.env, juno.config.ts, juno.json, package-lock.json, package.json, src/docs/services/analytics.services.ts, vite.config.js
Bring the cool stuffs.
- Upgrade analytics lib for breaking changes of last Juno release
- Analytics lib is a dependency, not dev dependency
- Transform json config into a TypeScript config file and add types to add intelisense in the editor
- Use Juno vite plugin to read and inject IDs instead of duplicating the values in env file
=> build: update Juno setup

package-lock.json, package.json
Consumers of the UI kit should not have to install the analytics library.
- npm rm && npm i -D
=> fix: analytics is a dev dependency

src/lib/components/QRCodeReaderModal.svelte
We would like to give the possibility to test the component.
Included prop `testId` miming the structure of the other components.
=> chore: add testId to QRCodeReaderModal for possible end-to-end tests

package-lock.json, package.json
Let's release a version.
No CHANGELOG update. Changes find place in GitHub release content.
- Bump version of package.json.
=> chore: bump next version

package-lock.json, package.json
Update dompurify to stay up-to-date with the most recent improvements in term of safety.
=> build: bump dompurify

package-lock.json, package.json
The newest version of Juno Analytics gather and aggregate performance metrics using Web Vitals. This can be interesting for our design system to detect which components might lead to some UI flickering.
- Bump Juno Analytics.
=> feat: bump Juno Analytics to track Web Vitals in showcase

src/lib/components/Popover.svelte
Make LinkToCanister component function as expected in nnsDapp
stopPropagation on onClick and onKeypress in Popover are deleted
=> delete stopPropagation on onClick and onKeypress in Popover

src/lib/styles/global/colors.scss, src/lib/styles/themes/dark.scss, src/lib/styles/themes/light.scss
Currently, we have primitive colors with the same values. In this update, we consolidate them into a single value and replace references in the themes with non-deprecated ones that share the same value. None of them are used in the nns-dapp repo.
- Update CSS variables.
=> Replace same variables

src/lib/components/Toggle.svelte, src/tests/lib/components/Toggle.spec.ts
Useful to have a test ID for the toggle.
=> feat: add test id to Toggle

src/lib/icons.ts, src/lib/icons/IconDocument.svelte
A new icon is needed for the link to navigate to the Report page in the nns-dapp.
- New icon `IconDocument`
=> feat: add icon IcondDocument

src/lib/components/BottomSheet.svelte, src/lib/components/Island.svelte, src/lib/components/SplitPane.svelte, src/lib/components/StretchPane.svelte
Not that important but, I spotted few imports in the lib which were using `../` paths so corrected those with `$lib/`.
=> chore: replace few import paths ../ with $lib/

package-lock.json, package.json
https://github.com/advisories/GHSA-9crc-q9x8-hgqq
1. Ran `npm i vitest@2.1.9`.
=> Upgrade vitest from 2.1.1 to 2.1.9

src/lib/stores/theme.store.ts
Improve the types of the theme store by declaring interfaces as we commonly do nowadays.
=> chore: interfaces for theme store

package-lock.json, package.json, src/lib/utils/html.utils.ts, vitest.setup.ts
Resolve security warning [#39 ](https://github.com/dfinity/gix-components/security/dependabot/39)
- Bump dompurify to v3.2.4
- Use renamed function `beforeSanitizeAttributes`
- Remove dompurify types
- Adapt test by casting and remove optional argument for contructor to resolve below issues
```
src/lib/utils/html.utils.ts:54:32 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.
54       } else if (typeof global.DOMPurify.sanitize === "function") {
~~~~~~~~~
src/lib/utils/html.utils.ts:56:28 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.
56         domPurify = global.DOMPurify;
~~~~~~~~~
src/lib/utils/html.utils.ts:60:26 - error TS2769: No overload matches this call. …
```
=> feat: bump dompurify

src/lib/components/Spinner.svelte
Migrating component `Spinner` to Svelte 5.
=> feat: Migrate component `Spinner` to Svelte 5

src/lib/components/SegmentButton.svelte
Migrating component `SegmentButton` to Svelte 5.
=> feat: Migrate component `SegmentButton` to Svelte 5

src/lib/components/Copy.svelte
Migrating component `Copy` to Svelte 5.
=> feat: Migrate component `Copy` to Svelte 5

src/lib/components/Section.svelte, src/routes/(split)/components/section/+page.md
We need to migrate `Collapsible` to Svelte v5 to prevent a potential issue (#696). In order to do so, we should first migration `Section`.
- Migrate component Section to Svelte v5
=> feat: migrate Section to Svelte v5
